version: "2"
linters:
  enable:
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - dogsled
    - dupl
    - durationcheck
    - errchkjson
    - errorlint
    - gocritic
    - goheader
    - goprintffuncname
    - gosec
    - grouper
    - importas
    - makezero
    - misspell
    - nilnil
    - prealloc
    - predeclared
    - reassign
    - revive
    - staticcheck
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
  settings:
    gocritic:
      disabled-checks:
        - ifElseChain
        - singleCaseSwitch
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
